name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: 
      group: build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci

      - name: Build
        run: npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/.vitepress

  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      pages: write
      contents: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@main
